### ISSUE TITLE
Réunion could have a better flag

### ISSUE THREAD

**Issue by danielquinn** [lafeber/world-flags-sprite#24]
One of our users pointed us to [this document](http://www.science-sainte-rose.net/reflexions/Un%20drapeau%20pour%20la%20Reunion%20cotes%20et%20couleurs%20officielles.pdf) that explains the use of a more appropriate flag for Réunion.  If you could, it'd be nice if this project could make use of this flag instead of the one currently in use for `.re`.

Further information on this can be found [here](http://reunionweb.org/articles/2001/09/Patriotisme-et-drapeaux).

**Comment by aloxe** [comment]
Hi, when I look closer, Réunion is not the only French territory with problem.
gp, same as re. is using the administration logo instead of the flag
gf, tf and wf are missing.

See <a href="https://fr.wikipedia.org/wiki/Liste_des_drapeaux_des_r%C3%A9gions_et_territoires_fran%C3%A7ais#D.C3.A9partements_et_r.C3.A9gions_d.27outre-mer">list of french territories' flags</a>

**Comment by lafeber** [comment]
I'm hoping for a pull request that uses this icon set: https://www.gosquared.com/resources/flag-icons/

However, Reunion (.re) doesn't seem to be included there...

**Comment by aloxe** [comment]
Gosquared miss many flags and you already have some of them. I submitted them the flag for Réunion and so I did it for you too 
Pull request sent

**Comment by lafeber** [comment]
And merged.

**Comment by aloxe** [comment]
https://github.com/lafeber/world-flags-sprite/pull/36#event-326539657
This pull request is closed, but the aloxe:reunion-flag branch has unmerged commits.
