### ISSUE TITLE
How to use 16 pixels version?

### ISSUE THREAD

**Issue by marcolino** [lafeber/world-flags-sprite#33]
Bower loads flags32.css.
What if I need 16px version?
And, what if I need both versions (always waiting for a 24 pixels version... :-)

**Comment by lafeber** [comment]
@marcolino Good question, I don't have that much experience with bower :( You could pass an array as main argument in the bower config file but I don't think this is ideal since it just will just include both css files.

**Comment by PandiPanda69** [comment]
I know this question has been put more than a year ago, but it could probably help some beginners with Bower.

You have to override the dependency bower main files since it only loads flags32 by default.
So, edit you `bower.json` so it looks like this:
```json
{
  "name": "myProject",
  "version": "0.0.0",
  "dependencies": {
    
  },
  "overrides": {
    "world-flags-sprite":  {
      "main": [
        "stylesheets/flags32.css", 
        "stylesheets/flags16.css"
      ]    
    }
  }
}
```

It would be very great that @lafeber edits his `bower.json` to avoid overriding this. Just replace
```json
"main": "stylesheets/flags32.css"
```
by
```json
"main": [ 
    "stylesheets/flags32.css", 
    "stylesheets/flags16.css"
]
```

Cheers

**Comment by lafeber** [comment]
Fixed.
