### ISSUE TITLE
3-letter country codes

### ISSUE THREAD

**Issue by toobulkeh** [lafeber/world-flags-sprite#45]
It would be nice to support 2 letter and 3 letter ISO country codes -- some mapping technologies only support one or the other -- and translating between the two is a pain.

**Comment by lafeber** [comment]
I'd be happy to merge a pull request with this addition.

**Comment by ksanchezm** [comment]
Hi @lafeber, I found myself needing support for 3 letter ISO country codes too and since the issue is open I'm thinking of creating a PR to get this done. 

Adding another selector to each flag rule to support the 3 digit codes seems pretty straightforward; however since some folks may prefer 2 digits or 3 digits only to keep the CSS size small, we could add additional stylesheets for those cases. so we'd have:

a. CSS file with support for ISO-2 codes in either 16 or 32px sizes (that'd be what we currently have on the repo)
b. CSS file with support for ISO-3 codes in either 16 or 32px sizes
c. CSS file with support for both ISO-2 and ISO-3 country codes in either 16 or 32px size

Can you give me your thoughts on this?

**Comment by lafeber** [comment]
@ksanchezm I like the solution where there's two different css files, so if you create a PR with a new css file for ISO-3 (and updated Readme) it will be greatly appreciated!
